In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import pybaseball
import numpy as np
import pandas as pd
from scipy import stats
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# regular season

In [17]:
url = 'https://baseballsavant.mlb.com/leaderboard/pitch-tempo?game_type=Regular&n=q&season_end=2024&season_start=2020&split=yes&team=&type=Pit&with_team_only=1'

# Send a GET request to fetch the webpage content
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# Find all tables on the page
tables = soup.find('div', class_='article-template')


# Check if any tables are found
tmp = tables.find('script').string

In [18]:
script_content = tables.find('script').string

# Split the content into lines and strip each line
lines = [line.strip() for line in script_content.split('\n')]

In [19]:
df = pd.DataFrame(json.loads(lines[2:][1][6:-1]))

In [20]:
drop_col = ['start_year_lower','start_year','end_year','end_year_upper','key_name_display_club','num_teams','key_team_id','pitcher_searchable','key_file_code','key_name_abbrev','team_image_url']

In [23]:
df2 = df.loc[:, df.nunique() > 1]
df3 = df2.drop(columns=drop_col)
df3.rename(columns={'timeframe':'year'},inplace=True)
reg_df = df3.sort_values(by='entity_name')
reg_df['game_type'] = 'Regular'
reg_df.head()

,entity_id,entity_name,year,tot_n,freq_hot,freq_warm,freq_cold,median_seconds,tot_n_empty,freq_hot_empty,freq_warm_empty,freq_cold_empty,median_seconds_empty,tot_n_onbase,freq_hot_onbase,freq_warm_onbase,freq_cold_onbase,median_seconds_onbase,team_name,game_type
219,671096,"Abbott, Andrew",2023,845,0.414201,0.583432,0.002367,15.780,552,0.634058,0.364130,0.001812,14.385,293,0.000000,0.996587,0.003413,19.691,CIN,Regular
266,671096,"Abbott, Andrew",2024,1053,0.404558,0.594492,0.000950,15.778,693,0.606061,0.393939,0.000000,14.576,360,0.016667,0.980556,0.002778,18.411,CIN,Regular
737,676265,"Abbott, Cory",2022,358,0.229050,0.701117,0.069832,18.445,244,0.336066,0.651639,0.012295,16.119,114,0.000000,0.807018,0.192982,26.617,WSH,Regular
625,656061,"Abreu, Albert",2023,482,0.226141,0.763485,0.010373,17.466,250,0.384000,0.608000,0.008000,15.820,232,0.056034,0.931034,0.012931,19.229,NYY,Regular
1303,656061,"Abreu, Albert",2022,325,0.095385,0.830769,0.073846,20.480,187,0.165775,0.812834,0.021390,17.937,138,0.000000,0.855072,0.144928,23.341,MLB,Regular

In [24]:
reg_df.groupby('year')['tot_n'].min()

year
2020    120
2021    324
2022    325
2023    324
2024    324
Name: tot_n, dtype: int64

# Play off

In [31]:
url = 'https://baseballsavant.mlb.com/leaderboard/pitch-tempo?game_type=Playoff&n=q&season_end=2024&season_start=2020&split=yes&team=&type=Pit&with_team_only=1'
# Send a GET request to fetch the webpage content
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# Find all tables on the page
tables = soup.find('div', class_='article-template')

# Check if any tables are found
tmp = tables.find('script').string
script_content = tables.find('script').string
# Split the content into lines and strip each line
lines = [line.strip() for line in script_content.split('\n')]
df = pd.DataFrame(json.loads(lines[2:][1][6:-1]))

In [33]:
df2 = df.loc[:, df.nunique() > 1]
df3 = df2.drop(columns=drop_col)
df3.rename(columns={'timeframe':'year'},inplace=True)
po_df = df3.sort_values(by='entity_name')
po_df['game_type'] = 'Playoff'
po_df.head()

,entity_id,entity_name,year,tot_n,freq_hot,freq_warm,freq_cold,median_seconds,tot_n_empty,freq_hot_empty,...,freq_cold_empty,median_seconds_empty,tot_n_onbase,freq_hot_onbase,freq_warm_onbase,freq_cold_onbase,median_seconds_onbase,is_qualified,team_name,game_type
518,650556,"Abreu, Bryan",2022,82,0.012195,0.853659,0.134146,24.042,63.0,0.015873,...,0.111111,23.028,19.0,0.000000,0.789474,0.210526,25.997,0,HOU,Playoff
224,650556,"Abreu, Bryan",2023,49,0.061224,0.938776,0.000000,17.840,32.0,0.093750,...,0.000000,17.019,17.0,0.000000,1.000000,0.000000,18.799,0,HOU,Playoff
282,592094,"Adam, Jason",2024,34,0.000000,1.000000,0.000000,17.972,32.0,0.000000,...,0.000000,17.813,2.0,0.000000,1.000000,0.000000,19.999,0,MLB,Playoff
102,613534,"Adams, Austin",2020,16,0.000000,0.875000,0.125000,22.640,3.0,0.000000,...,0.000000,15.426,13.0,0.000000,0.846154,0.153846,25.739,0,SD,Playoff
86,645261,"Alcantara, Sandy",2020,78,0.397436,0.576923,0.025641,15.702,61.0,0.491803,...,0.016393,15.173,17.0,0.058824,0.882353,0.058824,21.298,0,MIA,Playoff

# merge

In [34]:
timer_df = pd.concat([reg_df,po_df])

In [35]:
timer_df.head()

,entity_id,entity_name,year,tot_n,freq_hot,freq_warm,freq_cold,median_seconds,tot_n_empty,freq_hot_empty,...,freq_cold_empty,median_seconds_empty,tot_n_onbase,freq_hot_onbase,freq_warm_onbase,freq_cold_onbase,median_seconds_onbase,team_name,game_type,is_qualified
219,671096,"Abbott, Andrew",2023,845,0.414201,0.583432,0.002367,15.780,552.0,0.634058,...,0.001812,14.385,293.0,0.000000,0.996587,0.003413,19.691,CIN,Regular,NaN
266,671096,"Abbott, Andrew",2024,1053,0.404558,0.594492,0.000950,15.778,693.0,0.606061,...,0.000000,14.576,360.0,0.016667,0.980556,0.002778,18.411,CIN,Regular,NaN
737,676265,"Abbott, Cory",2022,358,0.229050,0.701117,0.069832,18.445,244.0,0.336066,...,0.012295,16.119,114.0,0.000000,0.807018,0.192982,26.617,WSH,Regular,NaN
625,656061,"Abreu, Albert",2023,482,0.226141,0.763485,0.010373,17.466,250.0,0.384000,...,0.008000,15.820,232.0,0.056034,0.931034,0.012931,19.229,NYY,Regular,NaN
1303,656061,"Abreu, Albert",2022,325,0.095385,0.830769,0.073846,20.480,187.0,0.165775,...,0.021390,17.937,138.0,0.000000,0.855072,0.144928,23.341,MLB,Regular,NaN

In [36]:
timer_df.to_csv('../data/timer_data.csv',index=False)